import { Locale } from './locale.type';

export const arabicLocal: Locale = {
  lang: 'ar',
  data: {
    // Customer screen translations
    en: 'الانجليزية',
    ar: 'العربية',
    customer: {
      // Header
      restaurant: 'مطعم',
      restaurantLogo: 'شعار المطعم',
      // Table info
      seats: 'مقاعد',
      // Action buttons
      sending: 'جاري الإرسال...',
      viewMenu: 'عرض القائمة',
      callWaiter: 'استدعاء النادل',
      requestBill: 'طلب الفاتورة',
      assistance: 'مساعدة',
      customRequest: 'طلب مخصص',
      // Custom request form
      enterCustomRequest: 'أدخل طلبك المخصص',
      customRequestPlaceholder: 'مثال: مناديل إضافية من فضلك',
      sendCustomRequest: 'إرسال الطلب المخصص',
      // Request actions
      complete: 'إكمال',
      cancel: 'إلغاء',
      // Status messages
      waiterIsComing: 'النادل قادم!',
      requestSent: 'تم إرسال الطلب!',
      // Error messages
      invalidTableId: 'رقم الطاولة غير صحيح',
      tableNotRegistered: 'الطاولة غير مسجلة',
      // Footer
      followUs: 'تابعنا',
      allRightsReserved: 'جميع الحقوق محفوظة',
    },
    waiter: {
      // Header
      dashboard: 'لوحة تحكم النادل',
      restaurant: 'مطعم',
      restaurantLogo: 'شعار المطعم',
      // Stats badges
      pending: 'قيد الانتظار',
      inProgress: 'قيد التنفيذ',
      // Column headers
      pendingRequests: 'الطلبات المعلقة',
      inProgressRequests: 'قيد التنفيذ',
      // Table info
      table: 'طاولة',
      seats: 'مقاعد',
      // Status labels
      statusPending: 'قيد الانتظار',
      statusInProgress: 'قيد التنفيذ',
      // Action buttons
      acknowledge: 'تأكيد',
      complete: 'إكمال',
      // Empty states
      noPendingRequests: 'لا توجد طلبات معلقة',
      noActiveTasks: 'لا توجد مهام نشطة',
      // Request type labels
      callWaiter: 'استدعاء النادل',
      requestBill: 'طلب الفاتورة',
      assistance: 'مساعدة',
      customRequest: 'طلب مخصص',
    },
    // Snackbar messages
    snackbar: {
      close: 'إغلاق',
      ok: 'حسناً',
      // Success messages
      requestSent: 'تم إرسال الطلب! سيكون النادل معك قريباً.',
      requestCompleted: 'شكراً لك! تم إكمال الطلب.',
      requestCancelled: 'تم إلغاء الطلب',
      previousRequestActive: 'طلبك السابق لا يزال نشطاً',
      // Error messages
      enterMessage: 'الرجاء إدخال رسالة',
      tableNotFound: 'الطاولة غير موجودة',
      failedToLoadTable: 'فشل تحميل معلومات الطاولة',
      tenantSubdomainRequired: 'خطأ: مطلوب اسم النطاق الفرعي للمستأجر. يرجى الوصول عبر اسم النطاق الفرعي (مثل: a.localhost:4200)',
    },
    // Admin panel translations
    admin: {
      // Main admin panel
      title: 'لوحة الإدارة',
      dashboard: 'لوحة التحكم',
      logout: 'تسجيل الخروج',
      welcome: 'مرحباً',
      menu: {
        analytics: 'التحليلات',
        serviceRequests: 'طلبات الخدمة',
        tableManagement: 'إدارة الطاولات',
        userManagement: 'إدارة المستخدمين',
        tenantBranding: 'العلامة التجارية',
        requestTypeManagement: 'إدارة أنواع الطلبات',
        qrGenerator: 'مولد رمز QR',
        integrations: 'التكاملات',
      },
      // Request Types
      requestTypes: {
        title: 'إدارة أنواع الطلبات',
        subtitle: 'تكوين أنواع طلبات العملاء',
        create: 'إنشاء نوع طلب',
        createFirst: 'إنشاء أول نوع طلب',
        edit: 'تعديل نوع الطلب',
        delete: 'حذف نوع الطلب',
        noRequestTypes: 'لم يتم تكوين أنواع الطلبات بعد',
        // Form fields
        nameEn: 'الاسم بالإنجليزية',
        nameAr: 'الاسم بالعربية',
        nameEnPlaceholder: 'أدخل الاسم بالإنجليزية',
        nameArPlaceholder: 'أدخل الاسم بالعربية',
        icon: 'الأيقونة',
        order: 'الترتيب',
        active: 'نشط',
        inactive: 'غير نشط',
        displayOrder: 'ترتيب العرض',
        // Actions
        save: 'حفظ',
        update: 'تحديث',
        cancel: 'إلغاء',
        deleteConfirm: 'هل أنت متأكد من حذف هذا النوع من الطلبات؟',
        // Messages
        fillAllFields: 'الرجاء ملء جميع الحقول المطلوبة',
        createSuccess: 'تم إنشاء نوع الطلب بنجاح',
        createFailed: 'فشل إنشاء نوع الطلب',
        updateSuccess: 'تم تحديث نوع الطلب بنجاح',
        updateFailed: 'فشل تحديث نوع الطلب',
        deleteSuccess: 'تم حذف نوع الطلب بنجاح',
        deleteFailed: 'فشل حذف نوع الطلب',
        reorderSuccess: 'تم إعادة ترتيب أنواع الطلبات بنجاح',
        reorderFailed: 'فشل إعادة ترتيب أنواع الطلبات',
        toggleSuccess: 'تم تحديث حالة نوع الطلب',
        toggleFailed: 'فشل تحديث حالة نوع الطلب',
        loadFailed: 'فشل تحميل أنواع الطلبات',
      },
      // QR Generator
      qrGenerator: {
        title: 'مولد رمز QR',
        subtitle: 'إنشاء وتنزيل رموز QR لطاولاتك',
        refresh: 'تحديث',
        downloadAll: 'تنزيل الكل',
        syncToDatabase: 'مزامنة مع قاعدة البيانات',
        loadFromBackend: 'تحميل من الخادم',
        syncToDatabaseTooltip: 'حفظ عناوين QR في قاعدة البيانات لجميع الطاولات',
        loadFromBackendTooltip: 'تحميل رموز QR مع العناوين من API الخادم',
        copyUrl: 'نسخ الرابط',
        syncedFromBackend: 'متزامن من الخادم',
        loading: 'جاري تحميل الطاولات...',
        noTables: 'لم يتم العثور على طاولات',
        noTablesDesc: 'قم بإنشاء الطاولات في إدارة الطاولات لإنشاء رموز QR',
        tableNumber: 'رقم الطاولة',
        capacity: 'السعة',
        status: 'الحالة',
        print: 'طباعة',
      },
      // Analytics Dashboard
      analytics: {
        title: 'لوحة التحليلات',
        overview: 'نظرة عامة',
        totalRequests: 'إجمالي الطلبات',
        activeRequests: 'الطلبات النشطة',
        completedRequests: 'الطلبات المكتملة',
        averageResponseTime: 'متوسط وقت الاستجابة',
        requestsByType: 'الطلبات حسب النوع',
        requestsByTable: 'الطلبات حسب الطاولة',
        dailyTrends: 'الاتجاهات اليومية',
        weeklyTrends: 'الاتجاهات الأسبوعية',
        monthlyTrends: 'الاتجاهات الشهرية',
      },
      // Service Requests
      serviceRequests: {
        title: 'إدارة طلبات الخدمة',
        subtitle: 'مراقبة وإدارة طلبات العملاء',
        filters: 'الفلاتر',
        status: 'الحالة',
        type: 'النوع',
        allStatuses: 'جميع الحالات',
        allTypes: 'جميع الأنواع',
        pending: 'قيد الانتظار',
        acknowledged: 'تم الاعتراف',
        completed: 'مكتملة',
        cancelled: 'ملغية',
        callWaiter: 'استدعاء النادل',
        bill: 'الفاتورة',
        billRequest: 'طلب الفاتورة',
        assistance: 'المساعدة',
        custom: 'مخصص',
        clearAll: 'مسح الكل',
        refresh: 'تحديث',
        loadingRequests: 'جارٍ تحميل طلبات الخدمة...',
        loadingMessage: 'يرجى الانتظار أثناء جلب أحدث البيانات',
        tableName: 'اسم الطاولة',
        acknowledgedBy: 'تم الاعتراف بواسطة',
        notAcknowledged: 'لم يتم الاعتراف',
        createdAt: 'تاريخ الإنشاء',
        duration: 'المدة الزمنية',
        actions: 'الإجراءات',
        acknowledgeRequest: 'الاعتراف بالطلب',
        markCompleted: 'وضع علامة مكتمل',
        deleteRequest: 'حذف الطلب',
        noRequests: 'لم يتم العثور على طلبات خدمة',
        noRequestsMessage: 'جرب تعديل الفلاتر أو تحقق لاحقاً من الطلبات الجديدة.',
        clearFilters: 'مسح الفلاتر',
        showing: 'عرض',
        of: 'من',
        requests: 'طلبات',
        itemsPerPage: 'عناصر لكل صفحة',
        previousPage: 'الصفحة السابقة',
        nextPage: 'الصفحة التالية',
        page: 'صفحة',
        createdTime: 'وقت الإنشاء',
        table: 'الطاولة',
        loadFailed: 'فشل في تحميل طلبات الخدمة',
        statusUpdated: 'تم تحديث حالة الطلب بنجاح',
        statusUpdateFailed: 'فشل في تحديث حالة الطلب',
        confirmDelete: 'هل أنت متأكد من حذف طلب الخدمة هذا؟',
        deleteSuccess: 'تم حذف طلب الخدمة بنجاح',
        deleteFailed: 'فشل في حذف طلب الخدمة',
      },
      // Table Management
      tableManagement: {
        title: 'إدارة الطاولات',
        subtitle: 'إدارة طاولات المطعم',
        addTable: 'إضافة طاولة',
        createTable: 'إنشاء طاولة',
        editTable: 'تعديل الطاولة',
        deleteTable: 'حذف الطاولة',
        save: 'حفظ',
        cancel: 'إلغاء',
        edit: 'تعديل',
        delete: 'حذف',
        tablesList: 'قائمة الطاولات',
        manageTables: 'إدارة طاولات مطعمك',
        loadingTables: 'جارٍ تحميل الطاولات...',
        uuid: 'المعرف الفريد',
        tableNumber: 'رقم الطاولة',
        tableNumberPlaceholder: 'مثال: T-01، طاولة 5',
        name: 'الاسم',
        nameOptional: 'الاسم (اختياري)',
        namePlaceholder: 'مثال: قسم VIP',
        zone: 'المنطقة',
        zoneOptional: 'المنطقة (اختياري)',
        zonePlaceholder: 'مثال: خارجي، القاعة الرئيسية',
        capacity: 'السعة',
        capacityOptional: 'السعة (اختياري)',
        capacityPlaceholder: 'مثال: 4',
        capacityMinError: 'يجب أن يكون 1 على الأقل',
        status: 'الحالة',
        actions: 'الإجراءات',
        active: 'نشط',
        inactive: 'غير نشط',
        required: 'مطلوب',
        fillRequiredFields: 'يرجى ملء جميع الحقول المطلوبة',
        tableCreated: 'تم إنشاء الطاولة بنجاح',
        createTableError: 'فشل في إنشاء الطاولة',
        tableUpdated: 'تم تحديث الطاولة بنجاح',
        updateTableError: 'فشل في تحديث الطاولة',
        tableDeleted: 'تم حذف الطاولة بنجاح',
        deleteTableError: 'فشل في حذف الطاولة',
        confirmDelete: 'هل أنت متأكد من حذف هذه الطاولة؟',
        uuidCopied: 'تم نسخ المعرف الفريد!',
        copyUuidError: 'فشل في نسخ المعرف الفريد',
        loadTablesError: 'فشل في تحميل الطاولات',
      },
      // User Management
      userManagement: {
        title: 'إدارة المستخدمين',
        subtitle: 'إدارة مستخدمي الموظفين',
        addNewWaiter: 'إضافة نادل جديد',
        createWaiterDescription: 'إنشاء حساب نادل جديد لمطعمك',
        username: 'اسم المستخدم',
        usernamePlaceholder: 'مثال: john_waiter',
        usernameHint: 'اسم مستخدم فريد للدخول',
        email: 'البريد الإلكتروني',
        emailPlaceholder: 'waiter@example.com',
        emailHint: 'سيتم استخدامه للإشعارات',
        fullName: 'الاسم الكامل',
        fullNamePlaceholder: 'جون دو',
        fullNameHint: 'الاسم المعروض للنادل',
        initialPassword: 'كلمة المرور الأولية',
        passwordPlaceholder: '8 أحرف كحد أدنى',
        passwordHint: 'يمكن للنادل تغييرها لاحقاً',
        addWaiter: 'إضافة نادل',
        waiters: 'النوادل',
        loadingWaiters: 'جاري تحميل النوادل...',
        status: 'الحالة',
        active: 'نشط',
        inactive: 'غير نشط',
        restaurant: 'المطعم',
        na: 'غير متوفر',
        actions: 'الإجراءات',
        deactivateWaiter: 'إلغاء تفعيل النادل',
        activateWaiter: 'تفعيل النادل',
        changePassword: 'تغيير كلمة المرور',
        deleteWaiter: 'حذف النادل نهائياً',
        noWaiters: 'لا يوجد نوادل بعد',
        noWaitersDescription: 'ابدأ بإضافة نادلك الأول باستخدام النموذج أعلاه!',
        changePasswordFor: 'تغيير كلمة المرور لـ',
        newPassword: 'كلمة المرور الجديدة',
        confirmPassword: 'تأكيد كلمة المرور',
        strongPasswordHint: 'كلمة مرور قوية موصى بها',
        passwordMismatch: 'كلمات المرور غير متطابقة',
        updatePassword: 'تحديث كلمة المرور',
        cancel: 'إلغاء',
        fillRequiredFields: 'يرجى ملء جميع الحقول المطلوبة',
        waiterCreated: 'تم إنشاء النادل بنجاح',
        failedToCreateWaiter: 'فشل في إنشاء النادل',
        activated: 'تم التفعيل',
        deactivated: 'تم إلغاء التفعيل',
        failedToAction: 'فشل في {{action}} النادل',
        passwordsDoNotMatch: 'كلمات المرور غير متطابقة',
        passwordUpdated: 'تم تحديث كلمة المرور لـ {{name}}',
        failedToChangePassword: 'فشل في تغيير كلمة المرور',
        confirmDelete: 'هل أنت متأكد من حذف {{name}} نهائياً؟\n\nلا يمكن التراجع عن هذا الإجراء.',
        userRemoved: 'تم إزالة المستخدم',
        failedToDeleteWaiter: 'فشل في حذف النادل',
        failedToLoadUsers: 'فشل في تحميل المستخدمين',
      },
      // Request Type Management
      requestTypeManagement: {
        title: 'إدارة أنواع الطلبات',
        subtitle: 'تكوين أنواع طلبات العملاء',
        create: 'إنشاء نوع طلب',
        createFirst: 'إنشاء النوع الأول للطلب',
        edit: 'تعديل نوع الطلب',
        delete: 'حذف نوع الطلب',
        loading: 'جارٍ التحميل...',
        noRequestTypes: 'لم يتم تكوين أنواع الطلبات بعد',
        noRequestTypesMessage: 'ابدأ بإنشاء نوع الطلب الأول لمساعدة العملاء على التواصل بفعالية مع احتياجاتهم.',
        // Form fields
        nameEn: 'الاسم بالإنجليزية',
        nameAr: 'الاسم بالعربية',
        nameEnPlaceholder: 'أدخل الاسم بالإنجليزية',
        nameArPlaceholder: 'أدخل الاسم بالعربية',
        nameEnHint: 'اسم العرض بالإنجليزية',
        nameArHint: 'اسم العرض بالعربية',
        icon: 'الأيقونة',
        iconHint: 'اختر أيقونة تمثل نوع هذا الطلب',
        // Menu URL - Global setting for all restaurants
        menuUrlTitle: 'تكوين رابط القائمة',
        menuUrl: 'رابط القائمة',
        menuUrlPlaceholder: 'https://www.example.com',
        menuUrlHint: 'رابط قائمة مطعمك. سيتم عرضه لجميع العملاء.',
        saveMenuUrl: 'حفظ رابط القائمة',
        menuUrlSaved: 'تم حفظ رابط القائمة بنجاح',
        menuUrlSaveFailed: 'فشل في حفظ رابط القائمة',
        displayOrder: 'الترتيب',
        status: 'الحالة',
        actions: 'الإجراءات',
        active: 'نشط',
        inactive: 'غير نشط',
        clickToActivate: 'انقر لتفعيل نوع هذا الطلب',
        clickToDeactivate: 'انقر لإلغاء تفعيل نوع هذا الطلب',
        // Icon options
        iconNotifications: 'الإشعارات',
        iconReceipt: 'الإيصال',
        iconHelp: 'المساعدة',
        iconRestaurant: 'المطعم',
        iconRoomService: 'خدمة الغرفة',
        iconCafe: 'المقهى',
        iconSupport: 'وكيل الدعم',
        iconCart: 'عربة التسوق',
        iconEvent: 'الحدث',
        // Actions
        save: 'حفظ',
        update: 'تحديث',
        cancel: 'إلغاء',
        deleteConfirm: 'هل أنت متأكد من حذف "{{name}}؟"',
        // Messages
        fillAllFields: 'يرجى ملء جميع الحقول المطلوبة',
        createSuccess: 'تم إنشاء نوع الطلب بنجاح',
        createFailed: 'فشل في إنشاء نوع الطلب',
        updateSuccess: 'تم تحديث نوع الطلب بنجاح',
        updateFailed: 'فشل في تحديث نوع الطلب',
        deleteSuccess: 'تم حذف نوع الطلب بنجاح',
        deleteFailed: 'فشل في حذف نوع الطلب',
        reorderSuccess: 'تم إعادة ترتيب أنواع الطلبات بنجاح',
        reorderFailed: 'فشل في إعادة ترتيب أنواع الطلبات',
        toggleSuccess: 'تم تحديث حالة نوع الطلب',
        toggleFailed: 'فشل في تحديث حالة نوع الطلب',
        loadFailed: 'فشل في تحميل أنواع الطلبات',
      },
      // Tenant Branding
      tenantBranding: {
        title: 'العلامة التجارية',
        subtitle: 'تخصيص علامتك التجارية للمطعم',
        general: 'عام',
        restaurantName: 'اسم المطعم',
        restaurantNamePlaceholder: 'أدخل اسم المطعم',
        restaurantNameHint: 'اسم المطعم',
        nameRequired: 'الاسم مطلوب ويجب أن يكون بين 2-100 حرف',
        menuUrl: 'رابط القائمة',
        menuUrlPlaceholder: 'https://www.example.com',
        menuUrlHint: 'رابط قائمة مطعمك. سيتم عرضه لجميع العملاء.',
        customRequestEnabled: 'تفعيل الطلبات المخصصة',
        customRequestEnabledDescription: 'السماح للعملاء بإرسال طلبات نصية مخصصة بالإضافة إلى أنواع الطلبات المحددة مسبقاً.',
        customRequestEnabledHint: 'الطلبات المخصصة مفعلة. يمكن للعملاء إرسال رسائل مخصصة.',
        customRequestDisabledHint: 'الطلبات المخصصة معطلة. ستكون أنواع الطلبات المحددة مسبقاً فقط متاحة.',
        colors: 'الألوان',
        primaryColor: 'اللون الأساسي',
        primaryColorHint: 'لون العلامة التجارية الرئيسي',
        secondaryColor: 'اللون الثانوي',
        secondaryColorHint: 'لون العلامة التجارية الثانوي',
        accentColor: 'لون التأكيد',
        accentColorHint: 'لون التمييز',
        backgroundColor: 'لون الخلفية',
        backgroundColorHint: 'خلفية الصفحة',
        textColor: 'لون النص',
        textColorHint: 'لون النص الرئيسي',
        languageColor: 'لون زر اللغة',
        languageColorHint: 'اختر لون زر تبديل اللغة',
        typography: 'الخطوط',
        fontFamily: 'عائلة الخط',
        fontFamilyPlaceholder: 'Inter, sans-serif',
        fontFamilyHint: 'قيمة CSS font-family (مثل "Arial, sans-serif")',
        fontSize: 'حجم الخط',
        fontSizeHint: 'حجم الخط الأساسي (مثل "16px", "1rem")',
        fontWeight: 'وزن الخط',
        fontWeightHint: 'سمك الخط',
        light: 'خفيف (300)',
        normal: 'عادي (400)',
        medium: 'متوسط (500)',
        semiBold: 'شبه غامق (600)',
        bold: 'غامق (700)',
        background: 'الخلفية',
        backgroundPattern: 'نمط الخلفية',
        backgroundPatternHint: 'اختر نمط خلفية خفيف',
        none: 'لا شيء',
        dots: 'نقاط',
        stripes: 'خطوط',
        waves: 'موجات',
        squares: 'مربعات',
        gradientType: 'نوع التدرج',
        gradientTypeHint: 'اختر نمط تدرج الخلفية',
        solid: 'لون صلب',
        linear: 'تدرج خطي',
        radial: 'تدرج شعاعي',
        gradientStartColor: 'لون بداية التدرج',
        gradientEndColor: 'لون نهاية التدرج',
        gradientDirection: 'اتجاه التدرج',
        toRight: 'إلى اليمين',
        toLeft: 'إلى اليسار',
        toBottom: 'إلى الأسفل',
        toTop: 'إلى الأعلى',
        diagonal: 'قطري (45°)',
        resetToDefaults: 'إعادة تعيين للإعدادات الافتراضية',
        logos: 'الشعارات',
        logo: 'رابط الشعار',
        logoPlaceholder: 'https://example.com/logo.png',
        logoHint: 'رابط مباشر لصورة الشعار',
        orUploadFile: 'أو رفع ملف:',
        uploadLogo: 'رفع الشعار',
        favicon: 'رابط الأيقونة المفضلة',
        faviconPlaceholder: 'https://example.com/favicon.ico',
        faviconHint: 'رابط مباشر للأيقونة المفضلة',
        uploadFavicon: 'رفع الأيقونة المفضلة',
        logoPreview: 'معاينة الشعار:',
        socialMedia: 'وسائل التواصل الاجتماعي',
        facebook: 'رابط فيسبوك',
        facebookPlaceholder: 'https://facebook.com/yourpage',
        instagram: 'رابط إنستغرام',
        instagramPlaceholder: 'https://instagram.com/youraccount',
        twitter: 'رابط تويتر/X',
        twitterPlaceholder: 'https://twitter.com/youraccount',
        linkedin: 'رابط لينكدإن',
        linkedinPlaceholder: 'https://linkedin.com/company/yourcompany',
        advanced: 'متقدم',
        customCss: 'CSS مخصص',
        customCssPlaceholder: '/* أضف CSS مخصص هنا */\n.my-class { color: red; }',
        customCssHint: 'متقدم: أضف CSS مخصص للضبط الدقيق',
        warning: 'تحذير:',
        customCssWarning: 'CSS المخصص قد يؤدي إلى كسر التخطيط. استخدم بحذر!',
        preview: 'معاينة',
        sampleHeader: 'عنوان عينة',
        primaryButton: 'الزر الأساسي',
        secondaryButton: 'الزر الثانوي',
        accentButton: 'زر التأكيد',
        sampleText: 'هذا نص عينة بلون النص المختار.',
        sampleCard: 'بطاقة عينة',
        sampleCardText: 'معاينة كيف يبدو المظهر على العناصر المختلفة.',
        save: 'حفظ وتطبيق',
        testLive: 'اختبار مباشر',
        reset: 'إعادة تعيين',
        failedToLoadTenant: 'فشل في تحميل معلومات المستأجر',
        failedToLoadBranding: 'فشل في تحميل إعدادات العلامة التجارية',
        userOrTenantNotFound: 'المستخدم أو المستأجر غير موجود',
        saveSuccess: 'تم تحديث العلامة التجارية بنجاح! جاري تطبيق المظهر...',
        themeApplied: 'تم تطبيق المظهر! يمكنك رؤية التغييرات الآن.',
        saveFailed: 'فشل في تحديث العلامة التجارية',
        pleaseSelectImage: 'يرجى اختيار ملف صورة',
        fileSizeTooLarge: 'يجب أن يكون حجم الملف أقل من 2 ميجابايت',
        uploadNotImplemented: 'رفع الملفات إلى التخزين السحابي غير مطبق. استخدام المعاينة المحلية فقط. يرجى استخدام رابط مباشر للإنتاج.',
        previewApplied: 'تم تطبيق المعاينة! هذا مؤقت.',
        fillRequiredFields: 'يرجى ملء جميع الحقول المطلوبة',
      },
      // Integrations
      integrations: {
        title: 'التكاملات',
        subtitle: 'تكوين التكاملات الخارجية للطابعات والإنذارات والمزيد',
        loading: 'جارٍ تحميل التكاملات...',
        printer: {
          title: 'تكامل طابعة XPrinter (شبكة)',
          enable: 'تفعيل تكامل الطابعة',
          enabledHint: 'تكامل الطابعة مفعل',
          disabledHint: 'تكامل الطابعة معطل',
          description: 'تكوين طابعة XPrinter الشبكية للطباعة التلقائية لطلبات الخدمة (نفس أنظمة نقاط البيع)',
          ipAddress: 'عنوان IP للطابعة',
          ipPlaceholder: '192.168.1.100',
          ipHint: 'عنوان IP لطابعة XPrinter على الشبكة',
          ipRequired: 'عنوان IP مطلوب',
          port: 'المنفذ',
          portPlaceholder: '9100',
          portHint: 'منفذ الشبكة (افتراضي: 9100 للطباعة المباشرة)',
          portRequired: 'المنفذ مطلوب',
          name: 'اسم الطابعة (اختياري)',
          namePlaceholder: 'مثال: طابعة المطبخ',
          nameHint: 'اسم ودي للتعريف',
          paperWidth: 'عرض الورق',
          paperWidthHint: 'اختر عرض الورق لطابعتك الحرارية',
          language: 'لغة الطباعة',
          languageEn: 'الإنجليزية فقط',
          languageAr: 'العربية فقط',
          languageBoth: 'كلا اللغتين',
          languageHint: 'اختر اللغة (اللغات) التي تريد طباعة الإيصالات بها',
          autoPrint: 'طباعة الطلبات الجديدة تلقائياً',
          autoPrintHint: 'الطباعة التلقائية عند استلام طلب خدمة جديد',
          printHeader: 'طباعة الرأس',
          printHeaderHint: 'تضمين اسم المطعم والعنوان على الإيصال',
          printFooter: 'طباعة التذييل',
          printFooterHint: 'تضمين الطابع الزمني ورسالة الشكر على الإيصال',
          receiptPreview: 'معاينة الإيصال',
          receiptPreviewDescription: 'معاينة كيفية ظهور الطلبات على الإيصال المطبوع',
          save: 'حفظ إعدادات الطابعة',
          saveSuccess: 'تم حفظ إعدادات الطابعة بنجاح',
          test: 'اختبار الطباعة',
          testMessage: 'تم إرسال اختبار الطباعة إلى الطابعة',
        },
        alarm: {
          title: 'تكامل السماعة الشبكية',
          enable: 'تفعيل تكامل السماعة',
          enabledHint: 'تكامل السماعة مفعل',
          disabledHint: 'تكامل السماعة معطل',
          description: 'تكوين سماعة شبكية للتنبيهات الصوتية عند استلام طلبات خدمة جديدة',
          speakerIp: 'عنوان IP للسماعة',
          speakerIpPlaceholder: '192.168.1.101',
          speakerIpHint: 'عنوان IP للسماعة الشبكية',
          speakerIpRequired: 'عنوان IP للسماعة مطلوب',
          speakerPort: 'منفذ السماعة',
          speakerPortPlaceholder: '8080',
          speakerPortHint: 'منفذ الشبكة للتواصل مع السماعة',
          speakerPortRequired: 'منفذ السماعة مطلوب',
          soundType: 'نوع الصوت',
          beep: 'نغمة',
          alert: 'نغمة تنبيه',
          custom: 'صوت مخصص',
          soundTypeHint: 'اختر نوع الصوت المراد تشغيله',
          customSoundUrl: 'رابط الصوت المخصص',
          customSoundUrlPlaceholder: 'https://example.com/custom-alarm.mp3',
          customSoundUrlHint: 'رابط ملف صوت مخصص (يُستخدم فقط عند اختيار صوت مخصص)',
          volume: 'مستوى الصوت (%)',
          volumePlaceholder: '80',
          volumeHint: 'مستوى الصوت من 0 إلى 100',
          duration: 'المدة (ثواني)',
          durationPlaceholder: '5',
          durationHint: 'مدة تشغيل الإنذار',
          visualFlash: 'وميض مرئي',
          flashColor: 'لون الوميض',
          flashColorHint: 'لون وميض التنبيهات المرئية',
          save: 'حفظ إعدادات الإنذار',
          saveSuccess: 'تم حفظ إعدادات الإنذار بنجاح',
          test: 'اختبار الإنذار',
          testMessage: 'تم تفعيل اختبار الإنذار',
        },
        webhook: {
          title: 'إشعارات Webhook',
          enable: 'تفعيل إشعارات Webhook',
          enabledHint: 'إشعارات Webhook مفعلة',
          disabledHint: 'إشعارات Webhook معطلة',
          description: 'إرسال إشعارات فورية إلى الأنظمة الخارجية عبر Webhooks عند إنشاء أو تحديث طلبات الخدمة',
          url: 'رابط Webhook',
          urlPlaceholder: 'https://example.com/webhook',
          urlHint: 'الرابط الذي سيتم إرسال الإشعارات إليه',
          urlRequired: 'رابط Webhook مطلوب ويجب أن يكون رابطاً صالحاً',
          secretKey: 'المفتاح السري',
          secretKeyPlaceholder: 'اختياري: المفتاح السري لمصادقة Webhook',
          secretKeyHint: 'المفتاح السري الاختياري للتحقق من طلبات Webhook',
          events: 'أحداث الإشعارات',
          eventsDescription: 'اختر الأحداث التي يجب أن تطلق إشعارات Webhook',
          eventNewRequest: 'إنشاء طلب جديد',
          eventNewRequestHint: 'إرسال إشعار عند إنشاء طلب خدمة جديد',
          eventAcknowledged: 'تم الاعتراف بالطلب',
          eventAcknowledgedHint: 'إرسال إشعار عند الاعتراف بالطلب من قبل النادل',
          eventCompleted: 'اكتمال الطلب',
          eventCompletedHint: 'إرسال إشعار عند تحديد الطلب كمكتمل',
          eventCancelled: 'إلغاء الطلب',
          eventCancelledHint: 'إرسال إشعار عند إلغاء الطلب',
          advancedSettings: 'الإعدادات المتقدمة',
          retryAttempts: 'محاولات إعادة المحاولة',
          retryAttemptsPlaceholder: '3',
          retryAttemptsHint: 'عدد مرات إعادة المحاولة في حالة فشل Webhook (0-10)',
          timeout: 'الوقت الأقصى (مللي ثانية)',
          timeoutPlaceholder: '5000',
          timeoutHint: 'الوقت الأقصى للطلب بالمللي ثانية (1000-30000)',
          save: 'حفظ إعدادات Webhook',
          saveSuccess: 'تم حفظ إعدادات Webhook بنجاح',
          test: 'اختبار Webhook',
          testMessage: 'تم إرسال إشعار اختبار Webhook',
        },
      },
    },
  },
};