import { Locale } from './locale.type';

export const englishLocal: Locale = {
  lang: 'en',
  data: {
    // Customer screen translations
    en: 'English',
    ar: 'Arabic',
    customer: {
      // Header
      restaurant: 'Restaurant',
      restaurantLogo: 'Restaurant Logo',
      // Table info
      seats: 'seats',
      // Action buttons
      sending: 'Sending...',
      viewMenu: 'View Menu',
      callWaiter: 'Call Waiter',
      requestBill: 'Request Bill',
      assistance: 'Assistance',
      customRequest: 'Custom Request',
      // Custom request form
      enterCustomRequest: 'Enter your custom request',
      customRequestPlaceholder: 'e.g., Extra napkins please',
      sendCustomRequest: 'Send Custom Request',
      // Request actions
      complete: 'Complete',
      cancel: 'Cancel',
      // Status messages
      waiterIsComing: 'Waiter is coming!',
      requestSent: 'Request Sent!',
      // Error messages
      invalidTableId: 'Invalid Table ID',
      tableNotRegistered: 'Table is not registered',
      // Footer
      followUs: 'Follow Us',
      allRightsReserved: 'All rights reserved',
      // Feedback form
      feedbackTitle: 'How was your experience?',
      feedbackSubtitle: 'Your feedback helps us improve our service',
      rateService: 'Rate our service',
      additionalComments: 'Any additional comments or complaints?',
      commentsPlaceholder: 'Tell us about your experience...',
      helpUsImprove: 'Help us improve!',
      shareDetails: 'Share your details for exclusive offers and updates',
      yourName: 'Your Name',
      namePlaceholder: 'e.g., John Doe',
      nameOptional: '(Optional)',
      yourPhone: 'Your Phone',
      phonePlaceholder: 'e.g., +1234567890',
      phoneOptional: '(Optional)',
      submitFeedback: 'Submit Feedback',
      skipFeedback: 'Skip',
      thankYouFeedback: 'Thank you for your feedback!',
      feedbackSubmitted: 'Your feedback has been submitted successfully',
      activeRequests: 'Your Active Requests',
    },
    waiter: {
      // Header
      dashboard: 'Waiter Dashboard',
      restaurant: 'Restaurant',
      restaurantLogo: 'Restaurant Logo',
      // Stats badges
      pending: 'Pending',
      inProgress: 'In Progress',
      // Column headers
      pendingRequests: 'Pending Requests',
      inProgressRequests: 'In Progress',
      // Table info
      table: 'Table',
      seats: 'seats',
      // Status labels
      statusPending: 'Pending',
      statusInProgress: 'In Progress',
      // Action buttons
      acknowledge: 'Acknowledge',
      complete: 'Complete',
      customerMustComplete: 'Customer will complete',
      // Empty states
      noPendingRequests: 'No pending requests',
      noActiveTasks: 'No active tasks',
      // Request type labels
      callWaiter: 'Call Waiter',
      requestBill: 'Request Bill',
      assistance: 'Assistance',
      customRequest: 'Custom Request',
    },
    // Snackbar messages
    snackbar: {
      close: 'Close',
      ok: 'OK',
      // Success messages
      requestSent: 'Request Sent! A waiter will be with you shortly.',
      requestCompleted: 'Thank you! Request completed.',
      requestCancelled: 'Request cancelled',
      previousRequestActive: 'Your previous request is still active',
      // Error messages
      enterMessage: 'Please enter a message',
      pleaseRateService: 'Please rate our service before submitting',
      tableNotFound: 'Table not found',
      failedToLoadTable: 'Failed to load table information',
      tenantSubdomainRequired: 'Error: Tenant subdomain is required. Please access via subdomain (e.g., a.localhost:4200)',
    },
    // Admin panel translations
    admin: {
      // Main admin panel
      title: 'Admin Panel',
      dashboard: 'Dashboard',
      logout: 'Logout',
      welcome: 'Welcome',
      menu: {
        analytics: 'Analytics',
        serviceRequests: 'Service Requests',
        tableManagement: 'Table Management',
        userManagement: 'User Management',
        tenantBranding: 'Tenant Branding',
        requestTypeManagement: 'Request Type Management',
        qrGenerator: 'QR Code Generator',
        integrations: 'Integrations',
      },
      // Request Types
      requestTypes: {
        title: 'Request Type Management',
        subtitle: 'Configure customer request types',
        create: 'Create Request Type',
        createFirst: 'Create First Request Type',
        edit: 'Edit Request Type',
        delete: 'Delete Request Type',
        noRequestTypes: 'No request types configured yet',
        // Form fields
        nameEn: 'English Name',
        nameAr: 'Arabic Name',
        nameEnPlaceholder: 'Enter English name',
        nameArPlaceholder: 'Enter Arabic name',
        icon: 'Icon',
        order: 'Order',
        active: 'Active',
        inactive: 'Inactive',
        displayOrder: 'Display Order',
        // Actions
        save: 'Save',
        update: 'Update',
        cancel: 'Cancel',
        deleteConfirm: 'Are you sure you want to delete this request type?',
        // Messages
        fillAllFields: 'Please fill in all required fields',
        createSuccess: 'Request type created successfully',
        createFailed: 'Failed to create request type',
        updateSuccess: 'Request type updated successfully',
        updateFailed: 'Failed to update request type',
        deleteSuccess: 'Request type deleted successfully',
        deleteFailed: 'Failed to delete request type',
        reorderSuccess: 'Request types reordered successfully',
        reorderFailed: 'Failed to reorder request types',
        toggleSuccess: 'Request type status updated',
        toggleFailed: 'Failed to update request type status',
        loadFailed: 'Failed to load request types',
      },
      // QR Generator
      qrGenerator: {
        title: 'QR Code Generator',
        subtitle: 'Generate and download QR codes for your tables',
        refresh: 'Refresh',
        downloadAll: 'Download All',
        syncToDatabase: 'Sync to Database',
        loadFromBackend: 'Load from Backend',
        syncToDatabaseTooltip: 'Save QR URLs to database for all tables',
        loadFromBackendTooltip: 'Load QR codes with URLs from backend API',
        copyUrl: 'Copy URL',
        syncedFromBackend: 'Synced from Backend',
        loading: 'Loading tables...',
        noTables: 'No Tables Found',
        noTablesDesc: 'Create tables in Table Management to generate QR codes',
        tableNumber: 'Table Number',
        capacity: 'Capacity',
        status: 'Status',
        print: 'Print',
      },
      // Analytics Dashboard
      analytics: {
        title: 'Analytics Dashboard',
        overview: 'Overview',
        totalRequests: 'Total Requests',
        activeRequests: 'Active Requests',
        completedRequests: 'Completed Requests',
        averageResponseTime: 'Average Response Time',
        requestsByType: 'Requests by Type',
        requestsByTable: 'Requests by Table',
        dailyTrends: 'Daily Trends',
        weeklyTrends: 'Weekly Trends',
        monthlyTrends: 'Monthly Trends',
      },
      // Service Requests
      serviceRequests: {
        title: 'Service Requests Management',
        subtitle: 'Monitor and manage customer service requests',
        filters: 'Filters',
        status: 'Status',
        type: 'Type',
        allStatuses: 'All Statuses',
        allTypes: 'All Types',
        pending: 'Pending',
        acknowledged: 'Acknowledged',
        completed: 'Completed',
        cancelled: 'Cancelled',
        callWaiter: 'Call Waiter',
        bill: 'Bill',
        billRequest: 'Bill Request',
        assistance: 'Assistance',
        custom: 'Custom',
        clearAll: 'Clear All',
        refresh: 'Refresh',
        loadingRequests: 'Loading service requests...',
        loadingMessage: 'Please wait while we fetch the latest data',
        tableName: 'Table Name',
        acknowledgedBy: 'Acknowledged By',
        notAcknowledged: 'Not acknowledged',
        completedBy: 'Completed By',
        completedByWaiter: 'Waiter',
        completedByCustomer: 'Customer',
        feedback: 'Feedback',
        noFeedback: 'No feedback',
        createdAt: 'Created At',
        duration: 'Duration',
        actions: 'Actions',
        acknowledgeRequest: 'Acknowledge request',
        markCompleted: 'Mark as completed',
        deleteRequest: 'Delete request',
        noRequests: 'No service requests found',
        noRequestsMessage: 'Try adjusting your filters or check back later for new requests.',
        clearFilters: 'Clear Filters',
        showing: 'Showing',
        of: 'of',
        requests: 'requests',
        itemsPerPage: 'Items per page',
        previousPage: 'Previous page',
        nextPage: 'Next page',
        page: 'Page',
        createdTime: 'Created Time',
        table: 'Table',
        loadFailed: 'Failed to load service requests',
        statusUpdated: 'Request status updated successfully',
        statusUpdateFailed: 'Failed to update request status',
        confirmDelete: 'Are you sure you want to delete this service request?',
        deleteSuccess: 'Service request deleted successfully',
        deleteFailed: 'Failed to delete service request',
      },
      // Table Management
      tableManagement: {
        title: 'Table Management',
        subtitle: 'Manage restaurant tables',
        addTable: 'Add Table',
        createTable: 'Create Table',
        editTable: 'Edit Table',
        deleteTable: 'Delete Table',
        save: 'Save',
        cancel: 'Cancel',
        edit: 'Edit',
        delete: 'Delete',
        tablesList: 'Tables List',
        manageTables: 'Manage your restaurant tables',
        loadingTables: 'Loading tables...',
        uuid: 'UUID',
        tableNumber: 'Table Number',
        tableNumberPlaceholder: 'e.g., T-01, Table 5',
        name: 'Name',
        nameOptional: 'Name (Optional)',
        namePlaceholder: 'e.g., VIP Section',
        zone: 'Zone',
        zoneOptional: 'Zone (Optional)',
        zonePlaceholder: 'e.g., Outdoor, Main Hall',
        capacity: 'Capacity',
        capacityOptional: 'Capacity (Optional)',
        capacityPlaceholder: 'e.g., 4',
        capacityMinError: 'Must be at least 1',
        status: 'Status',
        actions: 'Actions',
        active: 'Active',
        inactive: 'Inactive',
        required: 'Required',
        fillRequiredFields: 'Please fill all required fields',
        tableCreated: 'Table created successfully',
        createTableError: 'Failed to create table',
        tableUpdated: 'Table updated successfully',
        updateTableError: 'Failed to update table',
        tableDeleted: 'Table deleted successfully',
        deleteTableError: 'Failed to delete table',
        confirmDelete: 'Are you sure you want to delete this table?',
        uuidCopied: 'UUID copied to clipboard!',
        copyUuidError: 'Failed to copy UUID',
        loadTablesError: 'Failed to load tables',
      },
      // User Management
      userManagement: {
        title: 'User Management',
        subtitle: 'Manage staff users',
        addNewWaiter: 'Add New Waiter',
        createWaiterDescription: 'Create a new waiter account for your restaurant',
        username: 'Username',
        usernamePlaceholder: 'e.g., john_waiter',
        usernameHint: 'Unique username for login',
        email: 'Email',
        emailPlaceholder: 'waiter@example.com',
        emailHint: 'Will be used for notifications',
        fullName: 'Full Name',
        fullNamePlaceholder: 'John Doe',
        fullNameHint: 'Display name for the waiter',
        initialPassword: 'Initial Password',
        passwordPlaceholder: 'Min 8 characters',
        passwordHint: 'Waiter can change this later',
        addWaiter: 'Add Waiter',
        waiters: 'Waiters',
        loadingWaiters: 'Loading waiters...',
        status: 'Status',
        active: 'Active',
        inactive: 'Inactive',
        restaurant: 'Restaurant',
        na: 'N/A',
        actions: 'Actions',
        deactivateWaiter: 'Deactivate waiter',
        activateWaiter: 'Activate waiter',
        changePassword: 'Change password',
        deleteWaiter: 'Delete waiter permanently',
        noWaiters: 'No waiters yet',
        noWaitersDescription: 'Get started by adding your first waiter using the form above!',
        changePasswordFor: 'Change Password for',
        newPassword: 'New Password',
        confirmPassword: 'Confirm Password',
        strongPasswordHint: 'Strong password recommended',
        passwordMismatch: 'Passwords do not match',
        updatePassword: 'Update Password',
        cancel: 'Cancel',
        fillRequiredFields: 'Please fill all required fields',
        waiterCreated: 'Waiter created successfully',
        failedToCreateWaiter: 'Failed to create waiter',
        activated: 'activated',
        deactivated: 'deactivated',
        failedToAction: 'Failed to {{action}} waiter',
        passwordsDoNotMatch: 'Passwords do not match',
        passwordUpdated: 'Password updated for {{name}}',
        failedToChangePassword: 'Failed to change password',
        confirmDelete: 'Are you sure you want to permanently delete {{name}}?\n\nThis action cannot be undone.',
        userRemoved: 'User removed',
        failedToDeleteWaiter: 'Failed to delete waiter',
        failedToLoadUsers: 'Failed to load users',
      },
      // Request Type Management
      requestTypeManagement: {
        title: 'Request Type Management',
        subtitle: 'Configure customer request types',
        create: 'Create Request Type',
        createFirst: 'Create First Request Type',
        edit: 'Edit Request Type',
        delete: 'Delete Request Type',
        loading: 'Loading...',
        noRequestTypes: 'No request types configured yet',
        noRequestTypesMessage: 'Get started by creating your first request type to help customers communicate their needs effectively.',
        // Form fields
        nameEn: 'English Name',
        nameAr: 'Arabic Name',
        nameEnPlaceholder: 'Enter English name',
        nameArPlaceholder: 'Enter Arabic name',
        nameEnHint: 'Display name in English',
        nameArHint: 'Display name in Arabic',
        icon: 'Icon',
        iconHint: 'Choose an icon that represents this request type',
        // Menu URL - Global setting for all restaurants
        menuUrlTitle: 'Menu URL Configuration',
        menuUrl: 'Menu URL',
        menuUrlPlaceholder: 'https://www.example.com',
        menuUrlHint: 'URL to your restaurant menu. This will be displayed to all customers.',
        saveMenuUrl: 'Save Menu URL',
        menuUrlSaved: 'Menu URL saved successfully',
        menuUrlSaveFailed: 'Failed to save menu URL',
        displayOrder: 'Display Order',
        status: 'Status',
        actions: 'Actions',
        active: 'Active',
        inactive: 'Inactive',
        clickToActivate: 'Click to activate this request type',
        clickToDeactivate: 'Click to deactivate this request type',
        // Icon options
        iconNotifications: 'Notifications',
        iconReceipt: 'Receipt',
        iconHelp: 'Help',
        iconRestaurant: 'Restaurant',
        iconRoomService: 'Room Service',
        iconCafe: 'Cafe',
        iconSupport: 'Support Agent',
        iconCart: 'Shopping Cart',
        iconEvent: 'Event',
        // Actions
        save: 'Save',
        update: 'Update',
        cancel: 'Cancel',
        deleteConfirm: 'Are you sure you want to delete "{{name}}"?',
        // Messages
        fillAllFields: 'Please fill in all required fields',
        createSuccess: 'Request type created successfully',
        createFailed: 'Failed to create request type',
        updateSuccess: 'Request type updated successfully',
        updateFailed: 'Failed to update request type',
        deleteSuccess: 'Request type deleted successfully',
        deleteFailed: 'Failed to delete request type',
        reorderSuccess: 'Request types reordered successfully',
        reorderFailed: 'Failed to reorder request types',
        toggleSuccess: 'Request type status updated',
        toggleFailed: 'Failed to update request type status',
        loadFailed: 'Failed to load request types',
      },
      // Tenant Branding
      tenantBranding: {
        title: 'Tenant Branding',
        subtitle: 'Customize your restaurant branding',
        general: 'General',
        restaurantName: 'Restaurant Name',
        restaurantNamePlaceholder: 'Enter restaurant name',
        restaurantNameHint: 'The name of your restaurant',
        nameRequired: 'Name is required and must be between 2-100 characters',
        menuUrl: 'Menu URL',
        menuUrlPlaceholder: 'https://www.example.com',
        menuUrlHint: 'URL to your restaurant menu. This will be displayed to all customers.',
        customRequestEnabled: 'Enable Custom Requests',
        customRequestEnabledDescription: 'Allow customers to send custom text requests in addition to predefined request types.',
        customRequestEnabledHint: 'Custom requests are enabled. Customers can send custom messages.',
        customRequestDisabledHint: 'Custom requests are disabled. Only predefined request types will be available.',
        waiterCanComplete: 'Allow Waiters to Complete Requests',
        waiterCanCompleteDescription: 'Show complete button in waiter dashboard. When disabled, only customers can complete requests.',
        waiterCanCompleteHint: 'Waiters can complete requests from their dashboard.',
        waiterCannotCompleteHint: 'Only customers can complete requests. Waiters cannot complete from dashboard.',
        colors: 'Colors',
        primaryColor: 'Primary Color',
        primaryColorHint: 'Main brand color',
        secondaryColor: 'Secondary Color',
        secondaryColorHint: 'Secondary brand color',
        accentColor: 'Accent Color',
        accentColorHint: 'Highlight color',
        backgroundColor: 'Background Color',
        backgroundColorHint: 'Page background',
        textColor: 'Text Color',
        textColorHint: 'Main text color',
        languageColor: 'Language Button Color',
        languageColorHint: 'Select color for the language switch button',
        typography: 'Typography',
        fontFamily: 'Font Family',
        fontFamilyPlaceholder: 'Inter, sans-serif',
        fontFamilyHint: 'CSS font-family value (e.g., "Arial, sans-serif")',
        fontSize: 'Font Size',
        fontSizeHint: 'Base font size (e.g., "16px", "1rem")',
        fontWeight: 'Font Weight',
        fontWeightHint: 'Font thickness',
        light: 'Light (300)',
        normal: 'Normal (400)',
        medium: 'Medium (500)',
        semiBold: 'Semi Bold (600)',
        bold: 'Bold (700)',
        background: 'Background',
        backgroundPattern: 'Background Pattern',
        backgroundPatternHint: 'Choose a subtle background pattern',
        none: 'None',
        dots: 'Dots',
        stripes: 'Stripes',
        waves: 'Waves',
        squares: 'Squares',
        christmas: 'Christmas',
        gradientType: 'Gradient Type',
        gradientTypeHint: 'Choose background gradient style',
        solid: 'Solid Color',
        linear: 'Linear Gradient',
        radial: 'Radial Gradient',
        gradientStartColor: 'Gradient Start Color',
        gradientEndColor: 'Gradient End Color',
        gradientDirection: 'Gradient Direction',
        toRight: 'To Right',
        toLeft: 'To Left',
        toBottom: 'To Bottom',
        toTop: 'To Top',
        diagonal: 'Diagonal (45°)',
        resetToDefaults: 'Reset to Defaults',
        logos: 'Logos',
        logo: 'Logo URL',
        logoPlaceholder: 'https://example.com/logo.png',
        logoHint: 'Direct URL to your logo image',
        orUploadFile: 'Or upload a file:',
        uploadLogo: 'Upload Logo',
        favicon: 'Favicon URL',
        faviconPlaceholder: 'https://example.com/favicon.ico',
        faviconHint: 'Direct URL to your favicon',
        uploadFavicon: 'Upload Favicon',
        logoPreview: 'Logo Preview:',
        socialMedia: 'Social Media',
        facebook: 'Facebook URL',
        facebookPlaceholder: 'https://facebook.com/yourpage',
        instagram: 'Instagram URL',
        instagramPlaceholder: 'https://instagram.com/youraccount',
        twitter: 'Twitter/X URL',
        twitterPlaceholder: 'https://twitter.com/youraccount',
        linkedin: 'LinkedIn URL',
        linkedinPlaceholder: 'https://linkedin.com/company/yourcompany',
        advanced: 'Advanced',
        customCss: 'Custom CSS',
        customCssPlaceholder: '/* Add custom CSS here */\n.my-class { color: red; }',
        customCssHint: 'Advanced: Add custom CSS for fine-tuning',
        warning: 'Warning:',
        customCssWarning: 'Custom CSS can break your layout. Use with caution!',
        preview: 'Preview',
        sampleHeader: 'Sample Header',
        primaryButton: 'Primary Button',
        secondaryButton: 'Secondary Button',
        accentButton: 'Accent Button',
        sampleText: 'This is sample text in your chosen text color.',
        sampleCard: 'Sample Card',
        sampleCardText: 'Preview how your theme looks on different elements.',
        save: 'Save & Apply',
        testLive: 'Test Live',
        reset: 'Reset',
        failedToLoadTenant: 'Failed to load tenant information',
        failedToLoadBranding: 'Failed to load branding settings',
        userOrTenantNotFound: 'User or tenant not found',
        saveSuccess: 'Branding updated successfully! Applying theme...',
        themeApplied: 'Theme applied! You can see the changes now.',
        saveFailed: 'Failed to update branding',
        pleaseSelectImage: 'Please select an image file',
        fileSizeTooLarge: 'File size must be less than 2MB',
        uploadNotImplemented: 'File upload to cloud storage not implemented. Using local preview only. Please use a direct URL for production.',
        previewApplied: 'Preview applied! This is temporary.',
        fillRequiredFields: 'Please fill in all required fields',
      },
      // Integrations
      integrations: {
        title: 'Integrations',
        subtitle: 'Configure external integrations for printers, alarms, and more',
        loading: 'Loading integrations...',
        printer: {
          title: 'XPrinter Integration (Network)',
          enable: 'Enable Printer Integration',
          enabledHint: 'Printer integration is enabled',
          disabledHint: 'Printer integration is disabled',
          description: 'Configure XPrinter network printer for automatic printing of service requests (same as POS systems)',
          ipAddress: 'Printer IP Address',
          ipPlaceholder: '192.168.1.100',
          ipHint: 'IP address of your XPrinter on the network',
          ipRequired: 'IP address is required',
          port: 'Port',
          portPlaceholder: '9100',
          portHint: 'Network port (default: 9100 for raw printing)',
          portRequired: 'Port is required',
          name: 'Printer Name (Optional)',
          namePlaceholder: 'e.g., Kitchen Printer',
          nameHint: 'Friendly name for identification',
          paperWidth: 'Paper Width',
          paperWidthHint: 'Select the paper width of your thermal printer',
          language: 'Print Language',
          languageEn: 'English Only',
          languageAr: 'Arabic Only',
          languageBoth: 'Both Languages',
          languageHint: 'Choose which language(s) to print receipts in',
          autoPrint: 'Auto Print New Requests',
          autoPrintHint: 'Automatically print when a new service request is received',
          printHeader: 'Print Header',
          printHeaderHint: 'Include restaurant name and address on receipt',
          printFooter: 'Print Footer',
          printFooterHint: 'Include timestamp and thank you message on receipt',
          receiptPreview: 'Receipt Preview',
          receiptPreviewDescription: 'Preview how orders will appear on the printed receipt',
          save: 'Save Printer Settings',
          saveSuccess: 'Printer settings saved successfully',
          test: 'Test Print',
          testMessage: 'Test print sent to printer',
        },
        alarm: {
          title: 'Network Speaker Integration',
          enable: 'Enable Speaker Integration',
          enabledHint: 'Speaker integration is enabled',
          disabledHint: 'Speaker integration is disabled',
          description: 'Configure network-based speaker for audio alerts when new service requests are received',
          speakerIp: 'Speaker IP Address',
          speakerIpPlaceholder: '192.168.1.101',
          speakerIpHint: 'IP address of your network speaker',
          speakerIpRequired: 'Speaker IP address is required',
          speakerPort: 'Speaker Port',
          speakerPortPlaceholder: '8080',
          speakerPortHint: 'Network port for speaker communication',
          speakerPortRequired: 'Speaker port is required',
          soundType: 'Sound Type',
          beep: 'Beep',
          alert: 'Alert Tone',
          custom: 'Custom Sound',
          soundTypeHint: 'Select the type of sound to play',
          customSoundUrl: 'Custom Sound URL',
          customSoundUrlPlaceholder: 'https://example.com/custom-alarm.mp3',
          customSoundUrlHint: 'URL to a custom sound file (only used when Custom Sound is selected)',
          volume: 'Volume (%)',
          volumePlaceholder: '80',
          volumeHint: 'Volume level from 0 to 100',
          duration: 'Duration (seconds)',
          durationPlaceholder: '5',
          durationHint: 'How long the alarm should play',
          visualFlash: 'Visual Flash',
          flashColor: 'Flash Color',
          flashColorHint: 'Color for visual flash alerts',
          save: 'Save Alarm Settings',
          saveSuccess: 'Alarm settings saved successfully',
          test: 'Test Alarm',
          testMessage: 'Test alarm triggered',
        },
        webhook: {
          title: 'Webhook Notifications',
          enable: 'Enable Webhook Notifications',
          enabledHint: 'Webhook notifications are enabled',
          disabledHint: 'Webhook notifications are disabled',
          description: 'Send real-time notifications to external systems via webhooks when service requests are created or updated',
          url: 'Webhook URL',
          urlPlaceholder: 'https://example.com/webhook',
          urlHint: 'The URL where notifications will be sent',
          urlRequired: 'Webhook URL is required and must be a valid URL',
          secretKey: 'Secret Key',
          secretKeyPlaceholder: 'Optional: Secret key for webhook authentication',
          secretKeyHint: 'Optional secret key to verify webhook requests',
          events: 'Notification Events',
          eventsDescription: 'Select which events should trigger webhook notifications',
          eventNewRequest: 'New Request Created',
          eventNewRequestHint: 'Send notification when a new service request is created',
          eventAcknowledged: 'Request Acknowledged',
          eventAcknowledgedHint: 'Send notification when a request is acknowledged by a waiter',
          eventCompleted: 'Request Completed',
          eventCompletedHint: 'Send notification when a request is marked as completed',
          eventCancelled: 'Request Cancelled',
          eventCancelledHint: 'Send notification when a request is cancelled',
          advancedSettings: 'Advanced Settings',
          retryAttempts: 'Retry Attempts',
          retryAttemptsPlaceholder: '3',
          retryAttemptsHint: 'Number of times to retry if webhook fails (0-10)',
          timeout: 'Timeout (ms)',
          timeoutPlaceholder: '5000',
          timeoutHint: 'Request timeout in milliseconds (1000-30000)',
          save: 'Save Webhook Settings',
          saveSuccess: 'Webhook settings saved successfully',
          test: 'Test Webhook',
          testMessage: 'Test webhook notification sent',
        },
      },
    },
    // Landing page translations
    landing: {
      platformName: 'Veasyo',
      tagline: 'Viber Easy Operation',
      subTagline: 'Streamline restaurant operations with instant waiter communication',
      heroDescription: 'Transform your restaurant service with instant, seamless communication. Customers call waiters with a tap, waiters respond in real-time. It\'s that simple.',
      getStarted: 'Get Started Free',
      seeHowItWorks: 'See How It Works',
      signIn: 'Sign In',
      features: 'Features',
      howItWorks: 'How It Works',
      benefits: 'Benefits',
      navFeatures: 'Features',
      navHowItWorks: 'How It Works',
      navBenefits: 'Benefits',
      // Features
      featureRealTime: 'Real-Time Waiter Calling',
      featureRealTimeDesc: 'Instant communication between customers and waiters via WebSocket technology. No more waiting or flagging down staff.',
      featureQRCode: 'QR Code Table Management',
      featureQRCodeDesc: 'Each table gets a unique QR code. Customers scan and instantly connect to your restaurant\'s service system.',
      featurePrinter: 'Printer Integration',
      featurePrinterDesc: 'Seamless integration with XPrinter thermal printers. Automatic receipt printing when customers make requests.',
      featureAudio: 'Audio Alerts',
      featureAudioDesc: 'Network speaker integration for instant audio notifications. Never miss a customer request with configurable sound alerts.',
      featureAnalytics: 'Analytics Dashboard',
      featureAnalyticsDesc: 'Track response times, request frequency, and service metrics. Make data-driven decisions to improve customer experience.',
      featureBranding: 'White-Label Branding',
      featureBrandingDesc: 'Fully customizable branding for each restaurant. Your colors, your logo, your identity - complete control over customer experience.',
      featureMultiTenant: 'Multi-Restaurant SaaS',
      featureMultiTenantDesc: 'Complete tenant isolation. Each restaurant operates independently with custom subdomains and isolated data.',
      featureWebhook: 'Webhook Integrations',
      featureWebhookDesc: 'Connect with your existing systems via webhooks. Real-time notifications to POS systems, booking platforms, and more.',
      featureFeedback: 'Customer Feedback',
      featureFeedbackDesc: 'Built-in feedback system. Collect ratings and comments directly from customers after service completion.',
      // Benefits
      benefitFaster: 'Faster Response Time',
      benefitSatisfaction: 'Customer Satisfaction Increase',
      benefitTrust: 'Restaurants Trust Veasyo',
      // How It Works
      howItWorksTitle: 'How It Works',
      howItWorksSubtitle: 'Three simple steps to transform your restaurant service',
      step1Title: 'Generate QR Codes',
      step1Desc: 'Create unique QR codes for each table. Print them and place them on tables for easy customer access.',
      step2Title: 'Customers Scan & Request',
      step2Desc: 'Customers scan the QR code with their phone and instantly access your service interface. One tap to call a waiter.',
      step3Title: 'Real-Time Response',
      step3Desc: 'Waiters receive instant notifications on their dashboard. They can acknowledge and track all requests in real-time.',
      // CTA
      ctaTitle: 'Ready to Transform Your Restaurant?',
      ctaText: 'Join hundreds of restaurants already using Veasyo to deliver exceptional customer service',
      startFreeTrial: 'Start Free Trial',
      // Footer
      footerRights: 'All rights reserved',
      // Illustration labels
      customerView: 'Customer View',
      waiterDashboard: 'Waiter Dashboard',
      adminPanel: 'Admin Management',
      // Interactive Demo
      interactiveDemoTitle: 'Try It Live',
      interactiveDemoSubtitle: 'Experience the full workflow - switch between customer, waiter, and admin views',
      // Common Requests Slider
      commonRequests: 'Common Customer Requests',
      commonRequestsSubtitle: 'Problems we solve instantly',
      requestWaiter: 'I need a waiter',
      requestOrder: 'I want to order',
      requestBill: 'I want the bill',
      requestWater: 'I need water',
      requestClean: 'Clean my table',
      requestHelp: 'I need help',
    },
  },
};
